name: Create and Auto-Merge Pull Request
on: [push]
jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR
          title: "New changes"
          body: "New changes in this PR"
          branch: "branch-name"
          delete-branch: true
          draft: false
      - name: Auto Merge Pull Request
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
          MERGE_LABELS: "automerge,!wip"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Automatic merge of PR"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
